import { Food } from "../types";
import { appState, saveState } from "./state";

export const COMMON_FOODS: Food[] = [
  {
    name: "Kuru Fasulye",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/11/kuru-fasulye-yemekcom.jpg",
    category: "Baklagiller",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 45,
    nutritionalInfo: { calories: 280, protein: 18, carbs: 45, fat: 2 },
    id: 1,
  },
  {
    name: "Nohut",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Kuru_fasulye.jpg/800px-Kuru_fasulye.jpg",
    category: "Baklagiller",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 42,
    nutritionalInfo: { calories: 280, protein: 18, carbs: 45, fat: 2 },
    id: 2,
  },
  {
    name: "Mercimek",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Kuru_fasulye.jpg/800px-Kuru_fasulye.jpg",
    category: "Baklagiller",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 40,
    nutritionalInfo: { calories: 280, protein: 18, carbs: 45, fat: 2 },
    id: 3,
  },
  {
    name: "Barbunya",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/8/84/Barbunya_pilaki.jpg",
    category: "Baklagiller",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 43,
    nutritionalInfo: { calories: 280, protein: 18, carbs: 45, fat: 2 },
    id: 4,
  },
  {
    name: "Bamya",
    image_url: "https://cdn.yemek.com/mnresize/1250/833/uploads/2015/07/bamya-yemekcom.jpg",
    category: "Sebze Yemekleri",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 55,
    nutritionalInfo: { calories: 180, protein: 4, carbs: 15, fat: 10 },
    id: 5,
  },
  {
    name: "Kabak",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Taze_fasulye.jpg/800px-Taze_fasulye.jpg",
    category: "Sebze Yemekleri",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 45,
    nutritionalInfo: { calories: 180, protein: 4, carbs: 15, fat: 10 },
    id: 6,
  },
  {
    name: "Taze Fasulye",
    image_url: "https://cdn.yemek.com/uploads/2019/05/tazefasulyefbb.jpg",
    category: "Sebze Yemekleri",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 50,
    nutritionalInfo: { calories: 180, protein: 4, carbs: 15, fat: 10 },
    id: 7,
  },
  {
    name: "Ispanak",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Taze_fasulye.jpg/800px-Taze_fasulye.jpg",
    category: "Sebze Yemekleri",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 48,
    nutritionalInfo: { calories: 180, protein: 4, carbs: 15, fat: 10 },
    id: 8,
  },
  {
    name: "Patlıcan Musakka",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/01/patlican-musakka-yemekcom.jpg",
    category: "Sebze Yemekleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 75,
    nutritionalInfo: { calories: 280, protein: 12, carbs: 18, fat: 18 },
    id: 9,
  },
  {
    name: "Pırasa Yemeği",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/1/12/Zeytinya%C4%9Fl%C4%B1_p%C4%B1rasa_%28with_rice%29.jpg",
    category: "Sebze Yemekleri",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 52,
    nutritionalInfo: { calories: 180, protein: 4, carbs: 15, fat: 10 },
    id: 30,
  },
  {
    name: "Pide",
    image_url: "https://cdn.yemek.com/mnresize/940/940/uploads/2018/07/pide-tarifleri-kategorisi.jpg",
    category: "Hamur İşleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 70,
    nutritionalInfo: { calories: 380, protein: 10, carbs: 55, fat: 14 },
    id: 32,
  },
  {
    name: "Lahmacun",
    image_url: "https://cdn.yemek.com/mnresize/1250/833/uploads/2020/04/lahmacun-yemekcom-1.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 55,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 33,
  },
  {
    name: "Simit",
    image_url: "https://cdn.yemek.com/mncrop/940/625/uploads/2019/04/simit-tarifi-son.jpg",
    category: "Kahvaltı",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 10,
    nutritionalInfo: { calories: 280, protein: 12, carbs: 22, fat: 16 },
    id: 36,
  },
  {
    name: "Adana Kebap",
    image_url: "https://images.weserv.nl/?url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F8%2F8e%2FDoner_kebab%252C_Istanbul%252C_Turkey.JPG%2F800px-Doner_kebab%252C_Istanbul%252C_Turkey.JPG",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 220,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 37,
  },
  {
    name: "Urfa Kebap",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Adana_kebabı.jpg/800px-Adana_kebabı.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 210,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 38,
  },
  {
    name: "Beyti Kebap",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Beyti_Kebap.jpg/800px-Beyti_Kebap.jpg",
    category: "Sokak Lezzetleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 180,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 39,
  },
  {
    name: "Döner Dürüm",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/f/f1/D%C3%BCr%C3%BCm_D%C3%B6ner.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 80,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 40,
  },
  {
    name: "Tavuk Döner",
    image_url: "https://cdn.yemek.com/mnresize/1250/833/uploads/2015/04/tavuk-doner-onecikan.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 65,
    nutritionalInfo: { calories: 380, protein: 28, carbs: 10, fat: 18 },
    id: 41,
  },
  {
    name: "İskender",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/%C4%B0skender_kebap.JPG/800px-%C4%B0skender_kebap.JPG",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 150,
    nutritionalInfo: { calories: 520, protein: 38, carbs: 18, fat: 28 },
    id: 43,
  },
  {
    name: "Şiş Kebap",
    image_url: "https://cdn.yemek.com/mnresize/1250/833/uploads/2023/04/sis-kebap-onecikan.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 170,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 44,
  },
  {
    name: "Tavuk Pilav",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Roasted_chicken_and_Turkish_pilaf.jpg",
    category: "Sokak Lezzetleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 55,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 45,
  },
  {
    name: "Kumpir",
    image_url: "https://cdn.yemek.com/mnresize/1250/833/uploads/2021/03/kumpir-yemekcom.jpg",
    category: "Sokak Lezzetleri",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: { calories: 380, protein: 8, carbs: 65, fat: 12 },
    id: 46,
  },
  {
    name: "Ayran",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Ayran.jpg/800px-Ayran.jpg",
    category: "İçecekler",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 12,
    nutritionalInfo: { calories: 65, protein: 4, carbs: 6, fat: 3 },
    id: 51,
  },
  {
    name: "Çay",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Turkish_tea_%C3%A7ay_ve_papatya.jpg",
    category: "Kahvaltı",
    subCategory: "drink",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 5,
    nutritionalInfo: { calories: 5, protein: 0, carbs: 1, fat: 0 },
    id: 176,
  },
  {
    name: "Türk Kahvesi",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Turkishcoffee.jpg",
    category: "Kahvaltı",
    subCategory: "drink",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 20,
    nutritionalInfo: { calories: 15, protein: 0, carbs: 3, fat: 0 },
    id: 172,
  },
  {
    name: "Sütlaç",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2019/05/sutlac-guncelleme-sunum-1.jpg",
    category: "Sütlü Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 85,
    nutritionalInfo: { calories: 280, protein: 6, carbs: 42, fat: 9 },
    id: 100,
  },
  {
    name: "Baklava",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2017/06/fistikli-baklava-yemekcom1.jpg",
    category: "Şerbetli Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 180,
    nutritionalInfo: { calories: 480, protein: 5, carbs: 72, fat: 18 },
    id: 101,
  },
  {
    name: "Künefe",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/05/kunefe-reels-yemekcom-1.jpg",
    category: "Şerbetli Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 220,
    nutritionalInfo: { calories: 480, protein: 5, carbs: 72, fat: 18 },
    id: 102,
  },
  {
    name: "Menemen",
    image_url: "https://cdn.yemek.com/mncrop/620/388/uploads/2023/10/menemen-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "main",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 40,
    nutritionalInfo: { calories: 280, protein: 12, carbs: 22, fat: 16 },
    id: 104,
  },
  {
    name: "Sahanda Yumurta",
    image_url: "https://cdn.yemek.com/mnresize/1250/833/uploads/2020/04/sahanda-yumurta-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "main",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 30,
    nutritionalInfo: { calories: 280, protein: 12, carbs: 22, fat: 16 },
    id: 105,
  },
  {
    name: "Omlet",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/05/omlet-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "main",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: { calories: 280, protein: 12, carbs: 22, fat: 16 },
    id: 106,
  },
  {
    name: "Tost",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/03/tost-sunum-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "main",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 25,
    nutritionalInfo: { calories: 380, protein: 10, carbs: 55, fat: 14 },
    id: 107,
  },
  {
    name: "Poğaça",
    image_url: "https://cdn.yemek.com/mncrop/620/388/uploads/2015/05/mayali-pogaca-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "bakery",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 30,
    nutritionalInfo: { calories: 380, protein: 10, carbs: 55, fat: 14 },
    id: 108,
  },
  {
    name: "Mercimek Çorbası",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Mercimek_Corba.jpg/800px-Mercimek_Corba.jpg",
    category: "Çorbalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: { calories: 120, protein: 5, carbs: 18, fat: 3 },
    id: 55,
  },
  {
    name: "Ezogelin Çorbası",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Ezogelin_corba.jpg/800px-Ezogelin_corba.jpg",
    category: "Çorbalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 38,
    nutritionalInfo: { calories: 120, protein: 5, carbs: 18, fat: 3 },
    id: 56,
  },
  {
    name: "Yayla Çorbası",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Yayla_ğorbası.jpg/800px-Yayla_ğorbası.jpg",
    category: "Çorbalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 32,
    nutritionalInfo: { calories: 120, protein: 5, carbs: 18, fat: 3 },
    id: 57,
  },
  {
    name: "Domates Çorbası",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Domates_%C3%A7orbas%C4%B1.jpg",
    category: "Çorbalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 30,
    nutritionalInfo: { calories: 120, protein: 5, carbs: 18, fat: 3 },
    id: 58,
  },
  {
    name: "Tarhana Çorbası",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Tarhana_%C3%A7orbas%C4%B1.jpg",
    category: "Çorbalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 36,
    nutritionalInfo: { calories: 120, protein: 5, carbs: 18, fat: 3 },
    id: 59,
  },
  {
    name: "İşkembe Çorbası",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Turkish_tripe_soup.jpg",
    category: "Çorbalar",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 70,
    nutritionalInfo: { calories: 150, protein: 12, carbs: 8, fat: 8 },
    id: 60,
  },
  {
    name: "Beyti",
    image_url: "https://images.weserv.nl/?url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F8%2F8e%2FDoner_kebab%252C_Istanbul%252C_Turkey.JPG%2F800px-Doner_kebab%252C_Istanbul%252C_Turkey.JPG",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 160,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 181,
  },
  {
    name: "Ali Nazik",
    image_url: "https://images.weserv.nl/?url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F8%2F8e%2FDoner_kebab%252C_Istanbul%252C_Turkey.JPG%2F800px-Doner_kebab%252C_Istanbul%252C_Turkey.JPG",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 190,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 182,
  },
  {
    name: "Karnıyarık",
    image_url: "https://images.weserv.nl/?url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2Fe%2Fe1%2FTaze_fasulye.jpg%2F800px-Taze_fasulye.jpg",
    category: "Sebze Yemekleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 95,
    nutritionalInfo: { calories: 280, protein: 12, carbs: 18, fat: 18 },
    id: 199,
  },
  {
    name: "İmambayıldı",
    image_url: "https://images.weserv.nl/?url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2Fe%2Fe1%2FTaze_fasulye.jpg%2F800px-Taze_fasulye.jpg",
    category: "Sebze Yemekleri",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 85,
    nutritionalInfo: { calories: 180, protein: 4, carbs: 15, fat: 10 },
    id: 200,
  },
  {
    name: "Güllaç",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/e3/G%C3%BClla%C3%A7_with_pomegranate.jpg",
    category: "Sütlü Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 120,
    nutritionalInfo: { calories: 280, protein: 6, carbs: 42, fat: 9 },
    id: 300,
  },
  {
    name: "Pizza",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2025/11/tam-olculu-ev-yapimi-pizza-tarifi.jpg",
    category: "Fast Food",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 150,
    nutritionalInfo: {
      calories: 850,
      protein: 35,
      carbs: 92,
      fat: 38,
    },
    id: 330,
  },
  {
    name: "Burger",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2022/08/ev-yapimi-hamburger-lezzet.jpg",
    category: "Fast Food",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 165,
    nutritionalInfo: {
      calories: 650,
      protein: 32,
      carbs: 45,
      fat: 35,
    },
    id: 331,
  },
  {
    name: "Kuzu Tandır",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2018/07/bby-tandir-yemekcom.jpg",
    category: "Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 680,
    nutritionalInfo: {
      calories: 520,
      protein: 42,
      carbs: 8,
      fat: 35,
    },
    id: 332,
  },
  {
    name: "Kadayıf",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2019/05/kadayif-tatlisi-tarifi-yeni.jpg",
    category: "Şerbetli Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 180,
    nutritionalInfo: {
      calories: 390,
      protein: 5,
      carbs: 72,
      fat: 18,
    },
    id: 333,
  },
  {
    name: "Kürdan Kebabı",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2025/01/kurdan-kebabi-tarifi.jpg",
    category: "Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 450,
    nutritionalInfo: {
      calories: 480,
      protein: 38,
      carbs: 15,
      fat: 28,
    },
    id: 334,
  },
  {
    name: "Döner Kebap",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Doner_kebab%2C_Istanbul%2C_Turkey.JPG/800px-Doner_kebab%2C_Istanbul%2C_Turkey.JPG",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 95,
    nutritionalInfo: {
      calories: 450,
      protein: 32,
      carbs: 28,
      fat: 22,
    },
    id: 335,
  },
  {
    name: "Tavuk But",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/tavuk-sis-yemekcom.jpg",
    category: "Izgara & Mangal",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 30,
    nutritionalInfo: {
      calories: 380,
      protein: 35,
      carbs: 5,
      fat: 22,
    },
    id: 336,
  },
  {
    name: "Kuzu Şiş",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/04/sis-kebap-onecikan.jpg",
    category: "Izgara & Mangal",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 140,
    nutritionalInfo: {
      calories: 420,
      protein: 38,
      carbs: 8,
      fat: 24,
    },
    id: 337,
  },
  {
    name: "Ciğer Şiş",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Liver_and_onions.jpg",
    category: "Izgara & Mangal",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 45,
    nutritionalInfo: {
      calories: 320,
      protein: 28,
      carbs: 6,
      fat: 18,
    },
    id: 338,
  },
  {
    name: "Hünkar Beğendi",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2021/03/hunkar-begendi-son-yemekcom.jpg",
    category: "Etli Yemekler",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 620,
    nutritionalInfo: {
      calories: 480,
      protein: 38,
      carbs: 18,
      fat: 26,
    },
    id: 339,
  },
  {
    name: "Kuzu Kapama",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2016/03/kuzu-kapama-tarifi.jpg",
    category: "Etli Yemekler",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 530,
    nutritionalInfo: {
      calories: 520,
      protein: 40,
      carbs: 12,
      fat: 32,
    },
    id: 340,
  },
  {
    name: "Kuzu Yahni",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2022/04/papaz-yahnisi-banu.jpg",
    category: "Etli Yemekler",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 590,
    nutritionalInfo: {
      calories: 450,
      protein: 38,
      carbs: 15,
      fat: 24,
    },
    id: 341,
  },
  {
    name: "Etli Barbunya",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/8/84/Barbunya_pilaki.jpg",
    category: "Etli Yemekler",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 300,
    nutritionalInfo: {
      calories: 380,
      protein: 28,
      carbs: 32,
      fat: 14,
    },
    id: 342,
  },
  {
    name: "Tavuk Yahni",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Roasted_chicken_and_Turkish_pilaf.jpg",
    category: "Etli Yemekler",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 110,
    nutritionalInfo: {
      calories: 350,
      protein: 32,
      carbs: 18,
      fat: 16,
    },
    id: 343,
  },
  {
    name: "Fırında Tavuk",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/tavuk-sis-yemekcom.jpg",
    category: "Etli Yemekler",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 120,
    nutritionalInfo: {
      calories: 380,
      protein: 35,
      carbs: 12,
      fat: 20,
    },
    id: 344,
  },
  {
    name: "Fırında Patates",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Kumpir2.jpg",
    category: "Etli Yemekler",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 55,
    nutritionalInfo: {
      calories: 220,
      protein: 4,
      carbs: 42,
      fat: 6,
    },
    id: 345,
  },
  {
    name: "Fırında Sebze",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2019/12/firinda-renkli-sebzeler-yemekcom.jpg",
    category: "Etli Yemekler",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 70,
    nutritionalInfo: {
      calories: 180,
      protein: 5,
      carbs: 28,
      fat: 6,
    },
    id: 346,
  },
  {
    name: "Güveç",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/02/guvec-yemekcom.jpg",
    category: "Etli Yemekler",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 460,
    nutritionalInfo: {
      calories: 420,
      protein: 32,
      carbs: 22,
      fat: 22,
    },
    id: 347,
  },
  {
    name: "Kapama",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2020/01/kapama.jpg",
    category: "Etli Yemekler",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 440,
    nutritionalInfo: {
      calories: 380,
      protein: 28,
      carbs: 28,
      fat: 16,
    },
    id: 348,
  },
  {
    name: "Pirinç Pilavı",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2020/09/pirinc-pilavi-yemekcom.jpg",
    category: "Pilavlar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 60,
    nutritionalInfo: {
      calories: 280,
      protein: 5,
      carbs: 58,
      fat: 2,
    },
    id: 349,
  },
  // Kahvaltılık Ürünler (ID: 350-365)
  {
    name: "Menemen",
    image_url: "https://cdn.yemek.com/mncrop/620/388/uploads/2023/10/menemen-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "main",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 30,
    nutritionalInfo: {
      calories: 150,
      protein: 8,
      carbs: 12,
      fat: 8,
    },
    id: 350,
  },
  {
    name: "Omlet",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/05/omlet-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "main",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: {
      calories: 180,
      protein: 12,
      carbs: 2,
      fat: 14,
    },
    id: 351,
  },
  {
    name: "Sahanda Yumurta",
    image_url: "https://cdn.yemek.com/mnresize/1250/833/uploads/2020/04/sahanda-yumurta-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "main",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 25,
    nutritionalInfo: {
      calories: 140,
      protein: 10,
      carbs: 1,
      fat: 10,
    },
    id: 352,
  },
  {
    name: "Tost",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/03/tost-sunum-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "main",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 20,
    nutritionalInfo: {
      calories: 220,
      protein: 10,
      carbs: 25,
      fat: 8,
    },
    id: 353,
  },
  {
    name: "Poğaça",
    image_url: "https://cdn.yemek.com/mncrop/620/388/uploads/2015/05/mayali-pogaca-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "bakery",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 25,
    nutritionalInfo: {
      calories: 240,
      protein: 6,
      carbs: 30,
      fat: 10,
    },
    id: 354,
  },
  {
    name: "Açma",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2020/08/sade-acma-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "bakery",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 20,
    nutritionalInfo: {
      calories: 220,
      protein: 5,
      carbs: 32,
      fat: 7,
    },
    id: 355,
  },
  {
    name: "Sigara Böreği",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2024/01/sigara-boregi-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "bakery",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: {
      calories: 280,
      protein: 8,
      carbs: 32,
      fat: 14,
    },
    id: 356,
  },
  {
    name: "Beyaz Peynir",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Beyaz_peynir_%282%29.jpg",
    category: "Kahvaltı",
    subCategory: "side",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 25,
    nutritionalInfo: {
      calories: 80,
      protein: 6,
      carbs: 1,
      fat: 6,
    },
    id: 357,
  },
  {
    name: "Taze Kaşar",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Beyaz_peynir_%282%29.jpg",
    category: "Kahvaltı",
    subCategory: "side",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 15,
    nutritionalInfo: {
      calories: 70,
      protein: 5,
      carbs: 0,
      fat: 5,
    },
    id: 358,
  },
  {
    name: "Ezine Peyniri",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/8/84/Ezine_peyniri.jpg",
    category: "Kahvaltı",
    subCategory: "side",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: {
      calories: 90,
      protein: 6,
      carbs: 1,
      fat: 7,
    },
    id: 359,
  },
  {
    name: "Zeytin",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/d/df/Breakfast_olives_1240774.jpg",
    category: "Kahvaltı",
    subCategory: "side",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 15,
    nutritionalInfo: {
      calories: 45,
      protein: 0,
      carbs: 3,
      fat: 4,
    },
    id: 360,
  },
  {
    name: "Çay",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Simit-2x.JPG/800px-Simit-2x.JPG",
    category: "Kahvaltı",
    subCategory: "drink",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 5,
    nutritionalInfo: {
      calories: 5,
      protein: 0,
      carbs: 1,
      fat: 0,
    },
    id: 361,
  },
  {
    name: "Türk Kahvesi",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Simit-2x.JPG/800px-Simit-2x.JPG",
    category: "Kahvaltı",
    subCategory: "drink",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 20,
    nutritionalInfo: {
      calories: 15,
      protein: 0,
      carbs: 3,
      fat: 0,
    },
    id: 362,
  },
  {
    name: "Portakal Suyu",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Orangejuice.jpg",
    category: "Kahvaltı",
    subCategory: "drink",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 30,
    nutritionalInfo: {
      calories: 80,
      protein: 1,
      carbs: 18,
      fat: 0,
    },
    id: 363,
  },
  {
    name: "Bal",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Honey_comb.jpg",
    category: "Kahvaltı",
    subCategory: "side",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 15,
    nutritionalInfo: {
      calories: 60,
      protein: 0,
      carbs: 16,
      fat: 0,
    },
    id: 364,
  },
  {
    name: "Tereyağ",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Butter_%28cropped%29.jpg",
    category: "Kahvaltı",
    subCategory: "side",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 5,
    nutritionalInfo: {
      calories: 70,
      protein: 0,
      carbs: 0,
      fat: 8,
    },
    id: 365,
  },
  // ========== FAZ 4: YENİ 40 YEMEK (ID: 366-405) ==========
  // PILAVLAR (8 yemek)
  {
    name: "Bulgur Pilavı",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/05/bulgur-pilavi-yemekcom.jpg",
    category: "Pilavlar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 45,
    nutritionalInfo: {
      calories: 280,
      protein: 8,
      carbs: 55,
      fat: 4,
    },
    id: 366,
  },
  {
    name: "Nohutlu Pilav",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2018/10/arpa-sehriyeli-pirinc-pilavi-yemekcom.jpg",
    category: "Pilavlar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 55,
    nutritionalInfo: {
      calories: 320,
      protein: 10,
      carbs: 58,
      fat: 5,
    },
    id: 367,
  },
  {
    name: "Tavuklu Pilav",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/tavuk-sis-yemekcom.jpg",
    category: "Pilavlar",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 85,
    nutritionalInfo: {
      calories: 380,
      protein: 22,
      carbs: 52,
      fat: 8,
    },
    id: 368,
  },
  {
    name: "Etli Pilav",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2016/12/etli-bulgur-pilavi-yemekcom.jpg",
    category: "Pilavlar",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 120,
    nutritionalInfo: {
      calories: 420,
      protein: 24,
      carbs: 48,
      fat: 14,
    },
    id: 369,
  },
  {
    name: "Sebzeli Pilav",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/firin-kabinda-sebzeli-pilav-yemekcom.jpg",
    category: "Pilavlar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 50,
    nutritionalInfo: {
      calories: 290,
      protein: 6,
      carbs: 54,
      fat: 5,
    },
    id: 370,
  },
  {
    name: "Mantarlı Pilav",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/tam-olculu-mantarli-pilav-yemekcom.jpg",
    category: "Pilavlar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 60,
    nutritionalInfo: {
      calories: 270,
      protein: 7,
      carbs: 50,
      fat: 5,
    },
    id: 371,
  },
  {
    name: "Domatesli Pilav",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/05/bulgur-pilavi-yemekcom.jpg",
    category: "Pilavlar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 45,
    nutritionalInfo: {
      calories: 260,
      protein: 6,
      carbs: 52,
      fat: 4,
    },
    id: 372,
  },
  {
    name: "İnce Pilav",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2020/09/tereyagli-pilav-one-cikan.jpg",
    category: "Pilavlar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 40,
    nutritionalInfo: {
      calories: 250,
      protein: 5,
      carbs: 50,
      fat: 4,
    },
    id: 373,
  },
  // MAKARNA (7 yemek - ID: 374-380)
  {
    name: "Spagetti Bolonez",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/kremali-makarna-yemekcom.jpg",
    category: "Makarna",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 95,
    nutritionalInfo: {
      calories: 450,
      protein: 20,
      carbs: 58,
      fat: 16,
    },
    id: 374,
  },
  {
    name: "Carbonara",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/kremali-makarna-yemekcom.jpg",
    category: "Makarna",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 110,
    nutritionalInfo: {
      calories: 520,
      protein: 18,
      carbs: 52,
      fat: 28,
    },
    id: 375,
  },
  {
    name: "Fırın Makarna",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/kremali-makarna-yemekcom.jpg",
    category: "Makarna",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 90,
    nutritionalInfo: {
      calories: 480,
      protein: 16,
      carbs: 56,
      fat: 22,
    },
    id: 376,
  },
  {
    name: "Kremalı Mantarlı Makarna",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/kremali-makarna-yemekcom.jpg",
    category: "Makarna",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 100,
    nutritionalInfo: {
      calories: 460,
      protein: 14,
      carbs: 54,
      fat: 24,
    },
    id: 377,
  },
  {
    name: "Penne Arrabiata",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/kremali-makarna-yemekcom.jpg",
    category: "Makarna",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 75,
    nutritionalInfo: {
      calories: 380,
      protein: 12,
      carbs: 58,
      fat: 14,
    },
    id: 378,
  },
  {
    name: "Fettuccine Alfredo",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/kremali-makarna-yemekcom.jpg",
    category: "Makarna",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 105,
    nutritionalInfo: {
      calories: 540,
      protein: 16,
      carbs: 52,
      fat: 30,
    },
    id: 379,
  },
  {
    name: "Lazanya",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/kremali-makarna-yemekcom.jpg",
    category: "Makarna",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 140,
    nutritionalInfo: {
      calories: 580,
      protein: 26,
      carbs: 48,
      fat: 32,
    },
    id: 380,
  },
  // ZEYTİNYAĞLILAR (6 yemek - ID: 381-386)
  {
    name: "Zeytinyağlı Enginar",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/01/patlican-musakka-yemekcom.jpg",
    category: "Zeytinyağlılar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 85,
    nutritionalInfo: {
      calories: 220,
      protein: 6,
      carbs: 28,
      fat: 12,
    },
    id: 381,
  },
  {
    name: "Zeytinyağlı Pırasa",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/01/patlican-musakka-yemekcom.jpg",
    category: "Zeytinyağlılar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 55,
    nutritionalInfo: {
      calories: 180,
      protein: 4,
      carbs: 22,
      fat: 10,
    },
    id: 382,
  },
  {
    name: "Zeytinyağlı Taze Fasulye",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/01/patlican-musakka-yemekcom.jpg",
    category: "Zeytinyağlılar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 60,
    nutritionalInfo: {
      calories: 190,
      protein: 6,
      carbs: 24,
      fat: 8,
    },
    id: 383,
  },
  {
    name: "Zeytinyağlı Bamya",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/01/patlican-musakka-yemekcom.jpg",
    category: "Zeytinyağlılar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 55,
    nutritionalInfo: {
      calories: 170,
      protein: 5,
      carbs: 20,
      fat: 8,
    },
    id: 384,
  },
  {
    name: "Zeytinyağlı Bakla",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/01/patlican-musakka-yemekcom.jpg",
    category: "Zeytinyağlılar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 50,
    nutritionalInfo: {
      calories: 200,
      protein: 10,
      carbs: 26,
      fat: 6,
    },
    id: 385,
  },
  {
    name: "Zeytinyağlı Kabak",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/01/patlican-musakka-yemekcom.jpg",
    category: "Zeytinyağlılar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 45,
    nutritionalInfo: {
      calories: 150,
      protein: 4,
      carbs: 18,
      fat: 8,
    },
    id: 386,
  },
  // BÖREK (5 yemek - ID: 387-391)
  {
    name: "Su Böreği",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2024/01/sigara-boregi-yemekcom.jpg",
    category: "Hamur İşleri",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 80,
    nutritionalInfo: {
      calories: 340,
      protein: 12,
      carbs: 42,
      fat: 14,
    },
    id: 387,
  },
  {
    name: "Peynirli Börek",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2024/01/sigara-boregi-yemekcom.jpg",
    category: "Hamur İşleri",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 65,
    nutritionalInfo: {
      calories: 320,
      protein: 10,
      carbs: 38,
      fat: 16,
    },
    id: 388,
  },
  {
    name: "Kıymalı Börek",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2024/01/sigara-boregi-yemekcom.jpg",
    category: "Hamur İşleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 85,
    nutritionalInfo: {
      calories: 380,
      protein: 16,
      carbs: 36,
      fat: 18,
    },
    id: 389,
  },
  {
    name: "Ispanaklı Börek",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2024/01/sigara-boregi-yemekcom.jpg",
    category: "Hamur İşleri",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 60,
    nutritionalInfo: {
      calories: 290,
      protein: 8,
      carbs: 36,
      fat: 14,
    },
    id: 390,
  },
  {
    name: "Patatesli Börek",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2024/01/sigara-boregi-yemekcom.jpg",
    category: "Hamur İşleri",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 55,
    nutritionalInfo: {
      calories: 310,
      protein: 7,
      carbs: 42,
      fat: 14,
    },
    id: 391,
  },
  // SALATALAR (4 yemek - ID: 392-395)
  {
    name: "Çoban Salatası",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/tavuk-sis-yemekcom.jpg",
    category: "Salatalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 40,
    nutritionalInfo: {
      calories: 120,
      protein: 3,
      carbs: 15,
      fat: 6,
    },
    id: 392,
  },
  {
    name: "Gavurdağı Salatası",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/tavuk-sis-yemekcom.jpg",
    category: "Salatalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 45,
    nutritionalInfo: {
      calories: 140,
      protein: 4,
      carbs: 16,
      fat: 7,
    },
    id: 393,
  },
  {
    name: "Mevsim Salatası",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/tavuk-sis-yemekcom.jpg",
    category: "Salatalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: {
      calories: 90,
      protein: 2,
      carbs: 12,
      fat: 4,
    },
    id: 394,
  },
  {
    name: "Piyaz",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/tavuk-sis-yemekcom.jpg",
    category: "Salatalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 50,
    nutritionalInfo: {
      calories: 180,
      protein: 8,
      carbs: 28,
      fat: 5,
    },
    id: 395,
  },
  // MEZELER (4 yemek - ID: 396-399)
  {
    name: "Cacık",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Mezeler",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: {
      calories: 80,
      protein: 4,
      carbs: 8,
      fat: 4,
    },
    id: 396,
  },
  {
    name: "Humus",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Mezeler",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 45,
    nutritionalInfo: {
      calories: 160,
      protein: 6,
      carbs: 18,
      fat: 8,
    },
    id: 397,
  },
  {
    name: "Haydari",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Mezeler",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 40,
    nutritionalInfo: {
      calories: 120,
      protein: 4,
      carbs: 6,
      fat: 9,
    },
    id: 398,
  },
  {
    name: "Muhammara",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Mezeler",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 50,
    nutritionalInfo: {
      calories: 140,
      protein: 4,
      carbs: 16,
      fat: 8,
    },
    id: 399,
  },
  // DENİZ ÜRÜNLERİ (4 yemek - ID: 400-403)
  {
    name: "Hamsi Tava",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2024/05/ciger-sis-yemekcom.jpg",
    category: "Deniz Ürünleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 120,
    nutritionalInfo: {
      calories: 280,
      protein: 24,
      carbs: 12,
      fat: 16,
    },
    id: 400,
  },
  {
    name: "Balık Izgara",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2024/05/ciger-sis-yemekcom.jpg",
    category: "Deniz Ürünleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 180,
    nutritionalInfo: {
      calories: 240,
      protein: 28,
      carbs: 4,
      fat: 12,
    },
    id: 401,
  },
  {
    name: "Midye Dolma",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2024/05/ciger-sis-yemekcom.jpg",
    category: "Deniz Ürünleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 60,
    nutritionalInfo: {
      calories: 160,
      protein: 12,
      carbs: 14,
      fat: 7,
    },
    id: 402,
  },
  {
    name: "Kalamar Tava",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2024/05/ciger-sis-yemekcom.jpg",
    category: "Deniz Ürünleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 140,
    nutritionalInfo: {
      calories: 260,
      protein: 20,
      carbs: 18,
      fat: 14,
    },
    id: 403,
  },
  // TATLILAR (2 yemek - ID: 404-405)
  {
    name: "Maraş Dondurması",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/10/elmali-strudel-yemekcom.jpg",
    category: "Sütlü Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: {
      calories: 200,
      protein: 4,
      carbs: 28,
      fat: 8,
    },
    id: 404,
  },
  {
    name: "Waffle",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/10/elmali-strudel-yemekcom.jpg",
    category: "Sütlü Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 85,
    nutritionalInfo: {
      calories: 420,
      protein: 8,
      carbs: 58,
      fat: 18,
    },
    id: 405,
  },
  // ========== FAZ 5: 60 YENİ YEMEK (ID: 406-465) ==========
  // ÇORBALAR (10 yemek - ID: 406-415)
  {
    name: "Tavuk Suyu Çorbası",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/tavuk-suyu-corba-yemekcom.jpg",
    category: "Çorbalar",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: { calories: 161, protein: 12, carbs: 14, fat: 6 },
    id: 406,
  },
  {
    name: "Şehriye Çorbası",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2024/01/sehriye-corbasi-yemekcom.jpg",
    category: "Çorbalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 30,
    nutritionalInfo: { calories: 133, protein: 4, carbs: 22, fat: 3 },
    id: 407,
  },
  {
    name: "Düğün Çorbası",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/09/dugun-corbasi-yemekcom.jpg",
    category: "Çorbalar",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 65,
    nutritionalInfo: { calories: 220, protein: 14, carbs: 18, fat: 10 },
    id: 408,
  },
  {
    name: "Yuvalama Çorbası",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/ezogelin-corbasi-yemekcom.jpg",
    category: "Çorbalar",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 75,
    nutritionalInfo: { calories: 280, protein: 16, carbs: 24, fat: 12 },
    id: 409,
  },
  {
    name: "Lebeniye Çorbası",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/03/yogurtlu-corba-tarifi-yemekcom.jpg",
    category: "Çorbalar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 40,
    nutritionalInfo: { calories: 145, protein: 6, carbs: 12, fat: 8 },
    id: 410,
  },
  {
    name: "Brokoli Çorbası",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/brokoli-corbasi-yemekcom.jpg",
    category: "Çorbalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 38,
    nutritionalInfo: { calories: 95, protein: 4, carbs: 10, fat: 4 },
    id: 411,
  },
  {
    name: "Un Çorbası",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/11/un-corbasi-yeni-one-cikan.jpg",
    category: "Çorbalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 25,
    nutritionalInfo: { calories: 180, protein: 4, carbs: 32, fat: 4 },
    id: 412,
  },
  {
    name: "Analı Kızlı Çorbası",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Çorbalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 42,
    nutritionalInfo: { calories: 165, protein: 5, carbs: 28, fat: 4 },
    id: 413,
  },
  {
    name: "Arabaşı Çorbası",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/09/dugun-corbasi-yemekcom.jpg",
    category: "Çorbalar",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 70,
    nutritionalInfo: { calories: 240, protein: 12, carbs: 20, fat: 12 },
    id: 414,
  },
  {
    name: "Bamya Çorbası",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/ezogelin-corbasi-yemekcom.jpg",
    category: "Çorbalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 45,
    nutritionalInfo: { calories: 110, protein: 3, carbs: 18, fat: 3 },
    id: 415,
  },
  // KEBAPLAR (10 yemek - ID: 416-425)
  {
    name: "Tepsi Kebabı",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2024/02/26-tepsi-kebabi-yemekcom.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 95,
    nutritionalInfo: { calories: 319, protein: 18, carbs: 12, fat: 22 },
    id: 416,
  },
  {
    name: "Cağ Kebabı",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2025/07/cag-kebabi-tarifi.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 150,
    nutritionalInfo: { calories: 420, protein: 28, carbs: 8, fat: 30 },
    id: 417,
  },
  {
    name: "Testi Kebabı",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2025/08/testi-kebabi-tarifi.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 180,
    nutritionalInfo: { calories: 480, protein: 26, carbs: 22, fat: 32 },
    id: 418,
  },
  {
    name: "Kağıt Kebabı",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2017/11/Firinda-Beyti-Kebabi-yemekcom.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 110,
    nutritionalInfo: { calories: 340, protein: 22, carbs: 10, fat: 24 },
    id: 419,
  },
  {
    name: "Orman Kebabı",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/11/patlican-yemekcom.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 105,
    nutritionalInfo: { calories: 310, protein: 20, carbs: 15, fat: 20 },
    id: 420,
  },
  {
    name: "Çökertme Kebabı",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2024/03/cokertme-kebabi-yemekcom.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 125,
    nutritionalInfo: { calories: 380, protein: 24, carbs: 18, fat: 24 },
    id: 421,
  },
  {
    name: "Pideli Köfte",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/06/yumurtali-pide-yemekcom.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 85,
    nutritionalInfo: { calories: 450, protein: 22, carbs: 42, fat: 22 },
    id: 422,
  },
  {
    name: "Patlıcanlı Kebap",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2018/06/patlicanli-kebap-site.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 115,
    nutritionalInfo: { calories: 360, protein: 20, carbs: 14, fat: 26 },
    id: 423,
  },
  {
    name: "Altı Ezmeli Kebap",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2025/05/alti-ezmeli-kebap-tarifiii.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 140,
    nutritionalInfo: { calories: 420, protein: 24, carbs: 12, fat: 30 },
    id: 424,
  },
  {
    name: "Ev Usulü Urfa Kebabı",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2019/01/ev-usulu-urfa-kebabi-yemekcom.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 100,
    nutritionalInfo: { calories: 390, protein: 26, carbs: 6, fat: 28 },
    id: 425,
  },
  // ========== FAZ 6: 40 YENİ YEMEK (ID: 426-465) ==========
  // ŞERBETLİ TATLILAR (8 yemek - ID: 426-433)
  {
    name: "Revani",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Şerbetli Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 55,
    nutritionalInfo: { calories: 480, protein: 5, carbs: 72, fat: 18 },
    id: 426,
  },
  {
    name: "Şekerpare",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Şerbetli Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 50,
    nutritionalInfo: { calories: 480, protein: 5, carbs: 72, fat: 18 },
    id: 427,
  },
  {
    name: "İrmik Helvası",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Şerbetli Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 45,
    nutritionalInfo: { calories: 480, protein: 5, carbs: 72, fat: 18 },
    id: 428,
  },
  {
    name: "Ayva Tatlısı",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Şerbetli Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 60,
    nutritionalInfo: { calories: 480, protein: 5, carbs: 72, fat: 18 },
    id: 429,
  },
  {
    name: "Kabak Tatlısı",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Şerbetli Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 55,
    nutritionalInfo: { calories: 480, protein: 5, carbs: 72, fat: 18 },
    id: 430,
  },
  {
    name: "Tulumba Tatlısı",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Şerbetli Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 65,
    nutritionalInfo: { calories: 480, protein: 5, carbs: 72, fat: 18 },
    id: 431,
  },
  {
    name: "Un Helvası",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Şerbetli Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 40,
    nutritionalInfo: { calories: 480, protein: 5, carbs: 72, fat: 18 },
    id: 432,
  },
  {
    name: "Havuç Tatlısı",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Şerbetli Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 70,
    nutritionalInfo: { calories: 480, protein: 5, carbs: 72, fat: 18 },
    id: 433,
  },
  // SÜTLÜ TATLILAR (7 yemek - ID: 434-440)
  {
    name: "Kazandibi",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Sütlü Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 65,
    nutritionalInfo: { calories: 280, protein: 6, carbs: 42, fat: 9 },
    id: 434,
  },
  {
    name: "Tavuk Göğsü",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Sütlü Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 60,
    nutritionalInfo: { calories: 280, protein: 6, carbs: 42, fat: 9 },
    id: 435,
  },
  {
    name: "Supangle",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Sütlü Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 55,
    nutritionalInfo: { calories: 280, protein: 6, carbs: 42, fat: 9 },
    id: 436,
  },
  {
    name: "Keşkül",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Sütlü Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 50,
    nutritionalInfo: { calories: 280, protein: 6, carbs: 42, fat: 9 },
    id: 437,
  },
  {
    name: "Muhallebi",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Sütlü Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 45,
    nutritionalInfo: { calories: 280, protein: 6, carbs: 42, fat: 9 },
    id: 438,
  },
  {
    name: "Magnolia",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Sütlü Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 85,
    nutritionalInfo: { calories: 280, protein: 6, carbs: 42, fat: 9 },
    id: 439,
  },
  {
    name: "Güllaç",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Sütlü Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 90,
    nutritionalInfo: { calories: 280, protein: 6, carbs: 42, fat: 9 },
    id: 440,
  },
  // DOLMA & SARMA (10 yemek - ID: 441-450)
  {
    name: "Yaprak Sarması",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Dolma & Sarma",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 80,
    nutritionalInfo: { calories: 280, protein: 10, carbs: 38, fat: 8 },
    id: 441,
  },
  {
    name: "Biber Dolması",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Dolma & Sarma",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 75,
    nutritionalInfo: { calories: 280, protein: 10, carbs: 38, fat: 8 },
    id: 442,
  },
  {
    name: "Patlıcan Dolması",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Dolma & Sarma",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 85,
    nutritionalInfo: { calories: 280, protein: 10, carbs: 38, fat: 8 },
    id: 443,
  },
  {
    name: "Kabak Dolması",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Dolma & Sarma",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 70,
    nutritionalInfo: { calories: 280, protein: 10, carbs: 38, fat: 8 },
    id: 444,
  },
  {
    name: "Domates Dolması",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Dolma & Sarma",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 65,
    nutritionalInfo: { calories: 280, protein: 10, carbs: 38, fat: 8 },
    id: 445,
  },
  {
    name: "Lahana Sarması",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Dolma & Sarma",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 78,
    nutritionalInfo: { calories: 280, protein: 10, carbs: 38, fat: 8 },
    id: 446,
  },
  {
    name: "Kuru Fasulye Dolması",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Dolma & Sarma",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 72,
    nutritionalInfo: { calories: 280, protein: 10, carbs: 38, fat: 8 },
    id: 447,
  },
  {
    name: "Enginar Dolması",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Dolma & Sarma",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 95,
    nutritionalInfo: { calories: 280, protein: 10, carbs: 38, fat: 8 },
    id: 448,
  },
  {
    name: "Soğan Dolması",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Dolma & Sarma",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 68,
    nutritionalInfo: { calories: 280, protein: 10, carbs: 38, fat: 8 },
    id: 449,
  },
  {
    name: "Üzüm Yaprağı Sarması",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Dolma & Sarma",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 82,
    nutritionalInfo: { calories: 280, protein: 10, carbs: 38, fat: 8 },
    id: 450,
  },
  // İÇECEKLER (10 yemek - ID: 451-460)
  {
    name: "Kefir",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "İçecekler",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: { calories: 65, protein: 4, carbs: 6, fat: 3 },
    id: 451,
  },
  {
    name: "Soda",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "İçecekler",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 20,
    nutritionalInfo: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    id: 452,
  },
  {
    name: "Meyve Suyu",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "İçecekler",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 40,
    nutritionalInfo: { calories: 80, protein: 1, carbs: 18, fat: 0 },
    id: 453,
  },
  {
    name: "Limonata",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "İçecekler",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 45,
    nutritionalInfo: { calories: 65, protein: 0, carbs: 16, fat: 0 },
    id: 454,
  },
  {
    name: "Ice Tea",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "İçecekler",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: { calories: 45, protein: 0, carbs: 11, fat: 0 },
    id: 455,
  },
  {
    name: "Kola",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "İçecekler",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 40,
    nutritionalInfo: { calories: 140, protein: 0, carbs: 35, fat: 0 },
    id: 456,
  },
  {
    name: "Fanta",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "İçecekler",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 40,
    nutritionalInfo: { calories: 140, protein: 0, carbs: 35, fat: 0 },
    id: 457,
  },
  {
    name: "Sprite",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "İçecekler",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 40,
    nutritionalInfo: { calories: 140, protein: 0, carbs: 35, fat: 0 },
    id: 458,
  },
  {
    name: "Su",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "İçecekler",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 15,
    nutritionalInfo: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    id: 459,
  },
  {
    name: "Sade Soda",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "İçecekler",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 25,
    nutritionalInfo: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    id: 460,
  },
  // PİDE ÇEŞİTLERİ (5 yemek - ID: 461-465)
  {
    name: "Kaşarlı Pide",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Hamur İşleri",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 75,
    nutritionalInfo: { calories: 380, protein: 10, carbs: 55, fat: 14 },
    id: 461,
  },
  {
    name: "Sucuklu Pide",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Hamur İşleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 85,
    nutritionalInfo: { calories: 380, protein: 10, carbs: 55, fat: 14 },
    id: 462,
  },
  {
    name: "Pastırmalı Pide",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Hamur İşleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 90,
    nutritionalInfo: { calories: 380, protein: 10, carbs: 55, fat: 14 },
    id: 463,
  },
  {
    name: "Kavurmalı Pide",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Hamur İşleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 95,
    nutritionalInfo: { calories: 380, protein: 10, carbs: 55, fat: 14 },
    id: 464,
  },
  {
    name: "Karışık Pide",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2014/06/mercimek-corbasi-yemekcom.jpg",
    category: "Hamur İşleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 110,
    nutritionalInfo: { calories: 380, protein: 10, carbs: 55, fat: 14 },
    id: 465,
  },
];

const getNutritionByCategory = (category: string) => {
  switch (category) {
    case "Çorbalar":
      return { calories: 120, protein: 5, carbs: 18, fat: 3 };
    case "Baklagiller":
      return { calories: 280, protein: 18, carbs: 45, fat: 2 };
    case "Sebze Yemekleri":
      return { calories: 180, protein: 4, carbs: 15, fat: 10 };
    case "Izgara & Mangal":
    case "Döner & Kebap":
    case "Etli Yemekler":
      return { calories: 420, protein: 32, carbs: 12, fat: 24 };
    case "Hamur İşleri":
      return { calories: 380, protein: 10, carbs: 55, fat: 14 };
    case "Kahvaltı":
      return { calories: 280, protein: 12, carbs: 22, fat: 16 };
    case "Pilavlar":
      return { calories: 320, protein: 6, carbs: 58, fat: 8 };
    case "Makarna":
    case "Makarna & Pilav":
      return { calories: 450, protein: 14, carbs: 65, fat: 12 };
    case "Dolma & Sarma":
      return { calories: 280, protein: 10, carbs: 38, fat: 8 };
    case "Salatalar":
      return { calories: 140, protein: 5, carbs: 12, fat: 8 };
    case "Sütlü Tatlılar":
      return { calories: 280, protein: 6, carbs: 42, fat: 9 };
    case "Şerbetli Tatlılar":
      return { calories: 480, protein: 5, carbs: 72, fat: 18 };
    case "Meyveler":
      return { calories: 65, protein: 1, carbs: 16, fat: 0 };
    case "Deniz Ürünleri":
      return { calories: 220, protein: 28, carbs: 5, fat: 8 };
    default:
      return { calories: 250, protein: 8, carbs: 30, fat: 10 };
  }
};

export { getNutritionByCategory };
