import { Food } from "../types";
import { appState, saveState } from "./state";

export const COMMON_FOODS: Food[] = [
  {
    name: "Kuru Fasulye",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/11/kuru-fasulye-yemekcom.jpg",
    category: "Baklagiller",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 45,
    nutritionalInfo: { calories: 280, protein: 18, carbs: 45, fat: 2 },
    id: 1,
  },
  {
    name: "Nohut",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Kuru_fasulye.jpg/800px-Kuru_fasulye.jpg",
    category: "Baklagiller",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 42,
    nutritionalInfo: { calories: 280, protein: 18, carbs: 45, fat: 2 },
    id: 2,
  },
  {
    name: "Mercimek",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Kuru_fasulye.jpg/800px-Kuru_fasulye.jpg",
    category: "Baklagiller",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 40,
    nutritionalInfo: { calories: 280, protein: 18, carbs: 45, fat: 2 },
    id: 3,
  },
  {
    name: "Barbunya",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/8/84/Barbunya_pilaki.jpg",
    category: "Baklagiller",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 43,
    nutritionalInfo: { calories: 280, protein: 18, carbs: 45, fat: 2 },
    id: 4,
  },
  {
    name: "Bamya",
    image_url: "https://cdn.yemek.com/mnresize/1250/833/uploads/2015/07/bamya-yemekcom.jpg",
    category: "Sebze Yemekleri",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 55,
    nutritionalInfo: { calories: 180, protein: 4, carbs: 15, fat: 10 },
    id: 5,
  },
  {
    name: "Kabak",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Taze_fasulye.jpg/800px-Taze_fasulye.jpg",
    category: "Sebze Yemekleri",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 45,
    nutritionalInfo: { calories: 180, protein: 4, carbs: 15, fat: 10 },
    id: 6,
  },
  {
    name: "Taze Fasulye",
    image_url: "https://cdn.yemek.com/uploads/2019/05/tazefasulyefbb.jpg",
    category: "Sebze Yemekleri",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 50,
    nutritionalInfo: { calories: 180, protein: 4, carbs: 15, fat: 10 },
    id: 7,
  },
  {
    name: "Ispanak",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Taze_fasulye.jpg/800px-Taze_fasulye.jpg",
    category: "Sebze Yemekleri",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 48,
    nutritionalInfo: { calories: 180, protein: 4, carbs: 15, fat: 10 },
    id: 8,
  },
  {
    name: "Patlıcan Musakka",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/01/patlican-musakka-yemekcom.jpg",
    category: "Sebze Yemekleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 75,
    nutritionalInfo: { calories: 280, protein: 12, carbs: 18, fat: 18 },
    id: 9,
  },
  {
    name: "Pırasa Yemeği",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/1/12/Zeytinya%C4%9Fl%C4%B1_p%C4%B1rasa_%28with_rice%29.jpg",
    category: "Sebze Yemekleri",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 52,
    nutritionalInfo: { calories: 180, protein: 4, carbs: 15, fat: 10 },
    id: 30,
  },
  {
    name: "Pide",
    image_url: "https://cdn.yemek.com/mnresize/940/940/uploads/2018/07/pide-tarifleri-kategorisi.jpg",
    category: "Hamur İşleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 70,
    nutritionalInfo: { calories: 380, protein: 10, carbs: 55, fat: 14 },
    id: 32,
  },
  {
    name: "Lahmacun",
    image_url: "https://cdn.yemek.com/mnresize/1250/833/uploads/2020/04/lahmacun-yemekcom-1.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 55,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 33,
  },
  {
    name: "Simit",
    image_url: "https://cdn.yemek.com/mncrop/940/625/uploads/2019/04/simit-tarifi-son.jpg",
    category: "Kahvaltı",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 10,
    nutritionalInfo: { calories: 280, protein: 12, carbs: 22, fat: 16 },
    id: 36,
  },
  {
    name: "Adana Kebap",
    image_url: "https://images.weserv.nl/?url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F8%2F8e%2FDoner_kebab%252C_Istanbul%252C_Turkey.JPG%2F800px-Doner_kebab%252C_Istanbul%252C_Turkey.JPG",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 220,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 37,
  },
  {
    name: "Urfa Kebap",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Adana_kebabı.jpg/800px-Adana_kebabı.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 210,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 38,
  },
  {
    name: "Beyti Kebap",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Beyti_Kebap.jpg/800px-Beyti_Kebap.jpg",
    category: "Sokak Lezzetleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 180,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 39,
  },
  {
    name: "Döner Dürüm",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/f/f1/D%C3%BCr%C3%BCm_D%C3%B6ner.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 80,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 40,
  },
  {
    name: "Tavuk Döner",
    image_url: "https://cdn.yemek.com/mnresize/1250/833/uploads/2015/04/tavuk-doner-onecikan.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 65,
    nutritionalInfo: { calories: 380, protein: 28, carbs: 10, fat: 18 },
    id: 41,
  },
  {
    name: "İskender",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/%C4%B0skender_kebap.JPG/800px-%C4%B0skender_kebap.JPG",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 150,
    nutritionalInfo: { calories: 520, protein: 38, carbs: 18, fat: 28 },
    id: 43,
  },
  {
    name: "Şiş Kebap",
    image_url: "https://cdn.yemek.com/mnresize/1250/833/uploads/2023/04/sis-kebap-onecikan.jpg",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 170,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 44,
  },
  {
    name: "Tavuk Pilav",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Roasted_chicken_and_Turkish_pilaf.jpg",
    category: "Sokak Lezzetleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 55,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 45,
  },
  {
    name: "Kumpir",
    image_url: "https://cdn.yemek.com/mnresize/1250/833/uploads/2021/03/kumpir-yemekcom.jpg",
    category: "Sokak Lezzetleri",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: { calories: 380, protein: 8, carbs: 65, fat: 12 },
    id: 46,
  },
  {
    name: "Ayran",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Ayran.jpg/800px-Ayran.jpg",
    category: "İçecekler",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 12,
    nutritionalInfo: { calories: 65, protein: 4, carbs: 6, fat: 3 },
    id: 51,
  },
  {
    name: "Çay",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Simit-2x.JPG/800px-Simit-2x.JPG",
    category: "Kahvaltı",
    subCategory: "drink",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 5,
    nutritionalInfo: { calories: 5, protein: 0, carbs: 1, fat: 0 },
    id: 176,
  },
  {
    name: "Türk Kahvesi",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Simit-2x.JPG/800px-Simit-2x.JPG",
    category: "Kahvaltı",
    subCategory: "drink",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 20,
    nutritionalInfo: { calories: 15, protein: 0, carbs: 3, fat: 0 },
    id: 172,
  },
  {
    name: "Sütlaç",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2019/05/sutlac-guncelleme-sunum-1.jpg",
    category: "Sütlü Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 85,
    nutritionalInfo: { calories: 280, protein: 6, carbs: 42, fat: 9 },
    id: 100,
  },
  {
    name: "Baklava",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2017/06/fistikli-baklava-yemekcom1.jpg",
    category: "Şerbetli Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 180,
    nutritionalInfo: { calories: 480, protein: 5, carbs: 72, fat: 18 },
    id: 101,
  },
  {
    name: "Künefe",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/05/kunefe-reels-yemekcom-1.jpg",
    category: "Şerbetli Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 220,
    nutritionalInfo: { calories: 480, protein: 5, carbs: 72, fat: 18 },
    id: 102,
  },
  {
    name: "Menemen",
    image_url: "https://cdn.yemek.com/mncrop/620/388/uploads/2023/10/menemen-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "main",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 40,
    nutritionalInfo: { calories: 280, protein: 12, carbs: 22, fat: 16 },
    id: 104,
  },
  {
    name: "Sahanda Yumurta",
    image_url: "https://cdn.yemek.com/mnresize/1250/833/uploads/2020/04/sahanda-yumurta-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "main",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 30,
    nutritionalInfo: { calories: 280, protein: 12, carbs: 22, fat: 16 },
    id: 105,
  },
  {
    name: "Omlet",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/05/omlet-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "main",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: { calories: 280, protein: 12, carbs: 22, fat: 16 },
    id: 106,
  },
  {
    name: "Tost",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/03/tost-sunum-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "main",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 25,
    nutritionalInfo: { calories: 380, protein: 10, carbs: 55, fat: 14 },
    id: 107,
  },
  {
    name: "Poğaça",
    image_url: "https://cdn.yemek.com/mncrop/620/388/uploads/2015/05/mayali-pogaca-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "bakery",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 30,
    nutritionalInfo: { calories: 380, protein: 10, carbs: 55, fat: 14 },
    id: 108,
  },
  {
    name: "Mercimek Çorbası",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Mercimek_Corba.jpg/800px-Mercimek_Corba.jpg",
    category: "Çorbalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: { calories: 120, protein: 5, carbs: 18, fat: 3 },
    id: 55,
  },
  {
    name: "Ezogelin Çorbası",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Ezogelin_corba.jpg/800px-Ezogelin_corba.jpg",
    category: "Çorbalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 38,
    nutritionalInfo: { calories: 120, protein: 5, carbs: 18, fat: 3 },
    id: 56,
  },
  {
    name: "Yayla Çorbası",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Yayla_ğorbası.jpg/800px-Yayla_ğorbası.jpg",
    category: "Çorbalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 32,
    nutritionalInfo: { calories: 120, protein: 5, carbs: 18, fat: 3 },
    id: 57,
  },
  {
    name: "Domates Çorbası",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Domates_%C3%A7orbas%C4%B1.jpg",
    category: "Çorbalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 30,
    nutritionalInfo: { calories: 120, protein: 5, carbs: 18, fat: 3 },
    id: 58,
  },
  {
    name: "Tarhana Çorbası",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Tarhana_%C3%A7orbas%C4%B1.jpg",
    category: "Çorbalar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 36,
    nutritionalInfo: { calories: 120, protein: 5, carbs: 18, fat: 3 },
    id: 59,
  },
  {
    name: "İşkembe Çorbası",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Turkish_tripe_soup.jpg",
    category: "Çorbalar",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 70,
    nutritionalInfo: { calories: 150, protein: 12, carbs: 8, fat: 8 },
    id: 60,
  },
  {
    name: "Beyti",
    image_url: "https://images.weserv.nl/?url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F8%2F8e%2FDoner_kebab%252C_Istanbul%252C_Turkey.JPG%2F800px-Doner_kebab%252C_Istanbul%252C_Turkey.JPG",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 160,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 181,
  },
  {
    name: "Ali Nazik",
    image_url: "https://images.weserv.nl/?url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F8%2F8e%2FDoner_kebab%252C_Istanbul%252C_Turkey.JPG%2F800px-Doner_kebab%252C_Istanbul%252C_Turkey.JPG",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 190,
    nutritionalInfo: { calories: 420, protein: 32, carbs: 12, fat: 24 },
    id: 182,
  },
  {
    name: "Karnıyarık",
    image_url: "https://images.weserv.nl/?url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2Fe%2Fe1%2FTaze_fasulye.jpg%2F800px-Taze_fasulye.jpg",
    category: "Sebze Yemekleri",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 95,
    nutritionalInfo: { calories: 280, protein: 12, carbs: 18, fat: 18 },
    id: 199,
  },
  {
    name: "İmambayıldı",
    image_url: "https://images.weserv.nl/?url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2Fe%2Fe1%2FTaze_fasulye.jpg%2F800px-Taze_fasulye.jpg",
    category: "Sebze Yemekleri",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 85,
    nutritionalInfo: { calories: 180, protein: 4, carbs: 15, fat: 10 },
    id: 200,
  },
  {
    name: "Güllaç",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/e3/G%C3%BClla%C3%A7_with_pomegranate.jpg",
    category: "Sütlü Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 120,
    nutritionalInfo: { calories: 280, protein: 6, carbs: 42, fat: 9 },
    id: 300,
  },
  {
    name: "Pizza",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2025/11/tam-olculu-ev-yapimi-pizza-tarifi.jpg",
    category: "Fast Food",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 150,
    nutritionalInfo: {
      calories: 850,
      protein: 35,
      carbs: 92,
      fat: 38,
    },
    id: 330,
  },
  {
    name: "Burger",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2022/08/ev-yapimi-hamburger-lezzet.jpg",
    category: "Fast Food",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 165,
    nutritionalInfo: {
      calories: 650,
      protein: 32,
      carbs: 45,
      fat: 35,
    },
    id: 331,
  },
  {
    name: "Kuzu Tandır",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2018/07/bby-tandir-yemekcom.jpg",
    category: "Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 680,
    nutritionalInfo: {
      calories: 520,
      protein: 42,
      carbs: 8,
      fat: 35,
    },
    id: 332,
  },
  {
    name: "Kadayıf",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2019/05/kadayif-tatlisi-tarifi-yeni.jpg",
    category: "Şerbetli Tatlılar",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 180,
    nutritionalInfo: {
      calories: 390,
      protein: 5,
      carbs: 72,
      fat: 18,
    },
    id: 333,
  },
  {
    name: "Kürdan Kebabı",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2025/01/kurdan-kebabi-tarifi.jpg",
    category: "Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 450,
    nutritionalInfo: {
      calories: 480,
      protein: 38,
      carbs: 15,
      fat: 28,
    },
    id: 334,
  },
  {
    name: "Döner Kebap",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Doner_kebab%2C_Istanbul%2C_Turkey.JPG/800px-Doner_kebab%2C_Istanbul%2C_Turkey.JPG",
    category: "Döner & Kebap",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 95,
    nutritionalInfo: {
      calories: 450,
      protein: 32,
      carbs: 28,
      fat: 22,
    },
    id: 335,
  },
  {
    name: "Tavuk But",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/tavuk-sis-yemekcom.jpg",
    category: "Izgara & Mangal",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 30,
    nutritionalInfo: {
      calories: 380,
      protein: 35,
      carbs: 5,
      fat: 22,
    },
    id: 336,
  },
  {
    name: "Kuzu Şiş",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/04/sis-kebap-onecikan.jpg",
    category: "Izgara & Mangal",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 140,
    nutritionalInfo: {
      calories: 420,
      protein: 38,
      carbs: 8,
      fat: 24,
    },
    id: 337,
  },
  {
    name: "Ciğer Şiş",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Liver_and_onions.jpg",
    category: "Izgara & Mangal",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 45,
    nutritionalInfo: {
      calories: 320,
      protein: 28,
      carbs: 6,
      fat: 18,
    },
    id: 338,
  },
  {
    name: "Hünkar Beğendi",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Beyti_Kebap.jpg/800px-Beyti_Kebap.jpg",
    category: "Etli Yemekler",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 620,
    nutritionalInfo: {
      calories: 480,
      protein: 38,
      carbs: 18,
      fat: 26,
    },
    id: 339,
  },
  {
    name: "Kuzu Kapama",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Lamb_chops.jpg/800px-Lamb_chops.jpg",
    category: "Etli Yemekler",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 530,
    nutritionalInfo: {
      calories: 520,
      protein: 40,
      carbs: 12,
      fat: 32,
    },
    id: 340,
  },
  {
    name: "Kuzu Yahni",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Sirloin_steak.jpg/800px-Sirloin_steak.jpg",
    category: "Etli Yemekler",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 3,
    estimatedPrice: 590,
    nutritionalInfo: {
      calories: 450,
      protein: 38,
      carbs: 15,
      fat: 24,
    },
    id: 341,
  },
  {
    name: "Etli Barbunya",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/8/84/Barbunya_pilaki.jpg",
    category: "Etli Yemekler",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 300,
    nutritionalInfo: {
      calories: 380,
      protein: 28,
      carbs: 32,
      fat: 14,
    },
    id: 342,
  },
  {
    name: "Tavuk Yahni",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Roasted_chicken_and_Turkish_pilaf.jpg",
    category: "Etli Yemekler",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 110,
    nutritionalInfo: {
      calories: 350,
      protein: 32,
      carbs: 18,
      fat: 16,
    },
    id: 343,
  },
  {
    name: "Fırında Tavuk",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/12/tavuk-sis-yemekcom.jpg",
    category: "Etli Yemekler",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 120,
    nutritionalInfo: {
      calories: 380,
      protein: 35,
      carbs: 12,
      fat: 20,
    },
    id: 344,
  },
  {
    name: "Fırında Patates",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Kumpir2.jpg",
    category: "Etli Yemekler",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 55,
    nutritionalInfo: {
      calories: 220,
      protein: 4,
      carbs: 42,
      fat: 6,
    },
    id: 345,
  },
  {
    name: "Fırında Sebze",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/1/18/Kremal%C4%B1_sebze_%C3%A7orbas%C4%B1.jpg",
    category: "Etli Yemekler",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 70,
    nutritionalInfo: {
      calories: 180,
      protein: 5,
      carbs: 28,
      fat: 6,
    },
    id: 346,
  },
  {
    name: "Güveç",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Wedding_soup_from_the_Turkish_cuisine.jpg",
    category: "Etli Yemekler",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 460,
    nutritionalInfo: {
      calories: 420,
      protein: 32,
      carbs: 22,
      fat: 22,
    },
    id: 347,
  },
  {
    name: "Kapama",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/4/49/Nohut_yahni_and_bulgur.jpg",
    category: "Etli Yemekler",
    is_vegetarian: false,
    is_vegan: false,
    is_halal: true,
    priceLevel: 2,
    estimatedPrice: 440,
    nutritionalInfo: {
      calories: 380,
      protein: 28,
      carbs: 28,
      fat: 16,
    },
    id: 348,
  },
  {
    name: "Pirinç Pilavı",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/4/49/Nohut_yahni_and_bulgur.jpg",
    category: "Pilavlar",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 60,
    nutritionalInfo: {
      calories: 280,
      protein: 5,
      carbs: 58,
      fat: 2,
    },
    id: 349,
  },
  // Kahvaltılık Ürünler (ID: 350-365)
  {
    name: "Menemen",
    image_url: "https://cdn.yemek.com/mncrop/620/388/uploads/2023/10/menemen-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "main",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 30,
    nutritionalInfo: {
      calories: 150,
      protein: 8,
      carbs: 12,
      fat: 8,
    },
    id: 350,
  },
  {
    name: "Omlet",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/05/omlet-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "main",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: {
      calories: 180,
      protein: 12,
      carbs: 2,
      fat: 14,
    },
    id: 351,
  },
  {
    name: "Sahanda Yumurta",
    image_url: "https://cdn.yemek.com/mnresize/1250/833/uploads/2020/04/sahanda-yumurta-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "main",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 25,
    nutritionalInfo: {
      calories: 140,
      protein: 10,
      carbs: 1,
      fat: 10,
    },
    id: 352,
  },
  {
    name: "Tost",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2023/03/tost-sunum-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "main",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 20,
    nutritionalInfo: {
      calories: 220,
      protein: 10,
      carbs: 25,
      fat: 8,
    },
    id: 353,
  },
  {
    name: "Poğaça",
    image_url: "https://cdn.yemek.com/mncrop/620/388/uploads/2015/05/mayali-pogaca-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "bakery",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 25,
    nutritionalInfo: {
      calories: 240,
      protein: 6,
      carbs: 30,
      fat: 10,
    },
    id: 354,
  },
  {
    name: "Açma",
    image_url: "https://cdn.yemek.com/mncrop/620/388/uploads/2015/05/mayali-pogaca-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "bakery",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 20,
    nutritionalInfo: {
      calories: 220,
      protein: 5,
      carbs: 32,
      fat: 7,
    },
    id: 355,
  },
  {
    name: "Sigara Böreği",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/05/omlet-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "bakery",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: {
      calories: 280,
      protein: 8,
      carbs: 32,
      fat: 14,
    },
    id: 356,
  },
  {
    name: "Beyaz Peynir",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/05/omlet-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "side",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 25,
    nutritionalInfo: {
      calories: 80,
      protein: 6,
      carbs: 1,
      fat: 6,
    },
    id: 357,
  },
  {
    name: "Taze Kaşar",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/05/omlet-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "side",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 15,
    nutritionalInfo: {
      calories: 70,
      protein: 5,
      carbs: 0,
      fat: 5,
    },
    id: 358,
  },
  {
    name: "Ezine Peyniri",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/05/omlet-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "side",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 35,
    nutritionalInfo: {
      calories: 90,
      protein: 6,
      carbs: 1,
      fat: 7,
    },
    id: 359,
  },
  {
    name: "Zeytin",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/05/omlet-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "side",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 15,
    nutritionalInfo: {
      calories: 45,
      protein: 0,
      carbs: 3,
      fat: 4,
    },
    id: 360,
  },
  {
    name: "Çay",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Simit-2x.JPG/800px-Simit-2x.JPG",
    category: "Kahvaltı",
    subCategory: "drink",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 5,
    nutritionalInfo: {
      calories: 5,
      protein: 0,
      carbs: 1,
      fat: 0,
    },
    id: 361,
  },
  {
    name: "Türk Kahvesi",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Simit-2x.JPG/800px-Simit-2x.JPG",
    category: "Kahvaltı",
    subCategory: "drink",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 20,
    nutritionalInfo: {
      calories: 15,
      protein: 0,
      carbs: 3,
      fat: 0,
    },
    id: 362,
  },
  {
    name: "Portakal Suyu",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/05/omlet-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "drink",
    is_vegetarian: true,
    is_vegan: true,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 30,
    nutritionalInfo: {
      calories: 80,
      protein: 1,
      carbs: 18,
      fat: 0,
    },
    id: 363,
  },
  {
    name: "Bal",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/05/omlet-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "side",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 15,
    nutritionalInfo: {
      calories: 60,
      protein: 0,
      carbs: 16,
      fat: 0,
    },
    id: 364,
  },
  {
    name: "Tereyağ",
    image_url: "https://cdn.yemek.com/mncrop/600/315/uploads/2015/05/omlet-yemekcom.jpg",
    category: "Kahvaltı",
    subCategory: "side",
    is_vegetarian: true,
    is_vegan: false,
    is_halal: true,
    priceLevel: 1,
    estimatedPrice: 5,
    nutritionalInfo: {
      calories: 70,
      protein: 0,
      carbs: 0,
      fat: 8,
    },
    id: 365,
  },
];

const getNutritionByCategory = (category: string) => {
  switch (category) {
    case "Çorbalar":
      return { calories: 120, protein: 5, carbs: 18, fat: 3 };
    case "Baklagiller":
      return { calories: 280, protein: 18, carbs: 45, fat: 2 };
    case "Sebze Yemekleri":
      return { calories: 180, protein: 4, carbs: 15, fat: 10 };
    case "Izgara & Mangal":
    case "Döner & Kebap":
    case "Etli Yemekler":
      return { calories: 420, protein: 32, carbs: 12, fat: 24 };
    case "Hamur İşleri":
      return { calories: 380, protein: 10, carbs: 55, fat: 14 };
    case "Kahvaltı":
      return { calories: 280, protein: 12, carbs: 22, fat: 16 };
    case "Pilavlar":
      return { calories: 320, protein: 6, carbs: 58, fat: 8 };
    case "Makarna":
    case "Makarna & Pilav":
      return { calories: 450, protein: 14, carbs: 65, fat: 12 };
    case "Dolma & Sarma":
      return { calories: 280, protein: 10, carbs: 38, fat: 8 };
    case "Salatalar":
      return { calories: 140, protein: 5, carbs: 12, fat: 8 };
    case "Sütlü Tatlılar":
      return { calories: 280, protein: 6, carbs: 42, fat: 9 };
    case "Şerbetli Tatlılar":
      return { calories: 480, protein: 5, carbs: 72, fat: 18 };
    case "Meyveler":
      return { calories: 65, protein: 1, carbs: 16, fat: 0 };
    case "Deniz Ürünleri":
      return { calories: 220, protein: 28, carbs: 5, fat: 8 };
    default:
      return { calories: 250, protein: 8, carbs: 30, fat: 10 };
  }
};

export { getNutritionByCategory };
