const fs = require('fs');
const path = require('path');

// Yemeksepeti 2025 + Trendyol + Yemek.com popülerlik verileri
const popularityScores2025 = {
  // 🥇 Zirve Popüler (Yemeksepeti #1-5)
  'Tavuk Döner': 10,
  'Et Döner': 10,
  'Burger': 10,
  'Pizza': 10,
  'Kebap': 10,
  'Adana Kebap': 10,
  'Urfa Kebap': 10,
  'Lahmacun': 9,
  'Pide': 9,
  
  // 🍲 Çorbalar (Yemeksepeti verileri + Geleneksel)
  'Mercimek Çorbası': 9,
  'Ezogelin Çorbası': 9,
  'Tarhana Çorbası': 8,
  'Yayla Çorbası': 8,
  'Domates Çorbası': 8,
  'İşkembe Çorbası': 7,
  'Kelle Paça': 7,
  'Tavuk Suyu Çorbası': 7,
  
  // 🥩 Ana Yemekler (Etli)
  'İskender Kebap': 9,
  'Köfte': 10,
  'Izgara Köfte': 9,
  'İzmir Köfte': 8,
  'Karnıyarık': 9,
  'İmam Bayıldı': 9,
  'Hünkar Beğendi': 8,
  'Ali Nazik': 8,
  'Beyti': 8,
  'Kuzu Tandır': 8,
  'Testi Kebabı': 7,
  'Cağ Kebabı': 7,
  'Beyti Sarma': 7,
  'Tepsi Kebabı': 7,
  'Kağıt Kebabı': 7,
  'Orman Kebabı': 7,
  
  // 🍕 Global Lezzetler (Yemeksepeti #2-3)
  'Hamburger': 9,
  'Cheeseburger': 8,
  'Pizza': 9,
  'Margarita Pizza': 8,
  'Sucuklu Pizza': 8,
  'Tavuklu Pizza': 8,
  'Lazanya': 7,
  'Spagetti Bolonez': 7,
  'Fettuccine Alfredo': 7,
  'Kremalı Makarna': 7,
  
  // 🥟 Hamur İşleri
  'Mantı': 10,
  'Gözleme': 8,
  'Kıymalı Pide': 8,
  'Peynirli Pide': 8,
  'Kuşbaşılı Pide': 7,
  'Lahmacun': 9,
  'Börek': 8,
  'Sigara Böreği': 7,
  'Paçanga Böreği': 7,
  'Su Böreği': 7,
  
  // 🌿 Baklagiller & Sebze
  'Kuru Fasulye': 9,
  'Nohut': 8,
  'Barbunya Pilaki': 7,
  'Yeşil Mercimek': 7,
  'Nohut Pilav': 7,
  'Zeytinyağlı Enginar': 8,
  'Zeytinyağlı Pırasa': 7,
  'Zeytinyağlı Taze Fasulye': 7,
  'Zeytinyağlı Bamya': 6,
  'Zeytinyağlı Karnabahar': 6,
  'Taze Fasulye': 7,
  'Patlıcan Musakka': 7,
  'Bamya': 6,
  'Ispanak': 6,
  'Karnabahar': 6,
  
  // 🍳 Kahvaltı (Yemeksepeti Kahvaltı & Börek kategorisi)
  'Menemen': 10,
  'Sucuklu Yumurta': 10,
  'Pastırmalı Yumurta': 9,
  'Sahanda Yumurta': 9,
  'Omlet': 8,
  'Peynirli Omlet': 8,
  'Simit': 10,
  'Poğaça': 9,
  'Açma': 8,
  'Tost': 8,
  'Kaşarlı Tost': 8,
  'Sucuklu Tost': 8,
  'Börek': 8,
  'Kahvaltı Tabağı': 9,
  'Serpme Kahvaltı': 8,
  'Peynir': 8,
  'Beyaz Peynir': 8,
  'Kaşar Peyniri': 7,
  'Zeytin': 8,
  'Siyah Zeytin': 7,
  'Yeşil Zeytin': 7,
  'Bal': 7,
  'Kaymak': 7,
  'Tereyağı': 7,
  'Sürme Peynir': 7,
  'Nutella': 7,
  'Reçel': 7,
  'Tahin Pekmez': 7,
  'Kızarmış Ekmek': 7,
  'Pancake': 7,
  'Waffle': 7,
  
  // 🍰 Tatlılar
  'Baklava': 10,
  'Künefe': 10,
  'Sütlaç': 9,
  'Kadayıf': 9,
  'Revani': 8,
  'Şekerpare': 8,
  'İrmik Helvası': 8,
  'Aşure': 7,
  'Güllaç': 7,
  'Kazandibi': 7,
  'Tavuk Göğsü': 7,
  'Profiterol': 8,
  'Ekler': 7,
  'Pasta': 7,
  'Çikolatalı Pasta': 7,
  'Meyveli Pasta': 7,
  'Cheesecake': 7,
  'Brownie': 7,
  'Sufle': 7,
  'Waffle': 7,
  'Krep': 7,
  'Pankek': 7,
  'Dondurma': 8,
  'Maraş Dondurması': 7,
  
  // 🥤 İçecekler (Yemeksepeti verileri)
  'Ayran': 9,
  'Şalgam': 7,
  'Kefir': 6,
  'Çay': 10,
  'Türk Kahvesi': 10,
  'Soda': 7,
  'Meyve Suyu': 7,
  'Portakal Suyu': 7,
  'Elma Suyu': 6,
  'Limonata': 7,
  'Ice Tea': 6,
  'Kola': 6,
  'Fanta': 6,
  'Sprite': 6,
  'Su': 8,
  'Maden Suyu': 7,
  'Smoothie': 6,
  'Milkshake': 6,
  'Espresso': 7,
  'Cappuccino': 7,
  'Latte': 7,
  'Americano': 7,
  
  // 🥗 Salatalar & Mezeler
  'Çoban Salatası': 8,
  'Gavurdağı Salatası': 7,
  'Akdeniz Salatası': 7,
  'Sezar Salatası': 7,
  'Tavuklu Salata': 7,
  'Ton Balıklı Salata': 7,
  'Kısır': 8,
  'Piyaz': 7,
  'Humus': 7,
  'Cacık': 8,
  'Haydari': 6,
  'Babagannuş': 6,
  'Muhammara': 6,
  'Atom': 6,
  'Şakşuka': 6,
  'Girit Ezmesi': 6,
  'Acılı Ezme': 6,
  
  // 🍚 Pilav & Makarna
  'Pirinç Pilavı': 9,
  'Bulgur Pilavı': 8,
  'Nohutlu Pilav': 8,
  'Tavuklu Pilav': 8,
  'Etli Pilav': 8,
  'Mantarlı Pilav': 7,
  'Sebzeli Pilav': 7,
  'Spagetti': 7,
  'Fırın Makarna': 7,
  'Kremalı Mantarlı Makarna': 7,
  'Penne Arabiatta': 6,
  'Fettuccine': 6,
  
  // 🔥 Izgara
  'Tavuk Şiş': 8,
  'Köfte Izgara': 8,
  'Pirzola': 7,
  'Antrikot': 7,
  'Tavuk Pirzola': 7,
  'Sucuk Izgara': 7,
  'Pastırma': 7,
  'Sucuk': 7,
  'Bonfile': 7,
  'T-Bone Steak': 7,
  'New York Steak': 7,
  'Karışık Izgara': 8,
  'Tavuk Kanat': 7,
  'Tavuk But': 7,
  'Ciğer': 6,
  'Ciğer Tava': 6,
  
  // 🌯 Sokak Lezzetleri
  'Kumpir': 8,
  'Midye Dolma': 7,
  'Midye Tava': 7,
  'Kokoreç': 7,
  'Çiğ Köfte': 8,
  'Çiğ Köfte Dürüm': 7,
  'Tantuni': 7,
  'Tantuni Dürüm': 7,
  'Dürüm': 7,
  'Et Dürüm': 7,
  'Tavuk Dürüm': 7,
  'Köfte Dürüm': 7,
  'Balık Ekmek': 7,
  'Hamsi Tava': 6,
  'Patso': 6,
  'Sandviç': 7,
  'Tost': 8,
  'Ayvalık Tostu': 7,
  'Kumru': 6,
  'Sucuklu Yumurta': 9,
  
  // 🥙 Fast Food
  'Patates Kızartması': 8,
  'Soğan Halkası': 7,
  'Mozzarella Stick': 7,
  'Chicken Nugget': 7,
  'Hot Dog': 7,
  'Sosisli': 6,
  'Tavuk Burger': 8,
  'Balık Burger': 7,
  'Vegan Burger': 6,
  
  // 🧁 Atıştırmalıklar
  'Kızarmış Tavuk Kanat': 7,
  'Kızarmış Tavuk But': 7,
  'Kızarmış Tavuk Göğsü': 7,
  'Tavuk Nugget': 7,
  'Tavuk Popcorn': 7,
  'Kızarmış Kalamar': 7,
  'Karides Tava': 7,
  'Mantar Kızartma': 6,
  'Patlıcan Kızartma': 6,
  'Kabak Kızartma': 6,
  'Sigara Böreği': 7,
  'Paçanga Böreği': 7,
  'Sosisli Börek': 6,
  'Peynirli Börek': 6,
  'Zeytinli Açma': 6,
  'Patatesli Açma': 6,
  'Sucuklu Açma': 6,
  
  // 🍲 Ev Yemekleri (Yemeksepeti kategorisi)
  'Tas Kebabı': 7,
  'Kuzu İncik': 7,
  'Kuzu Kapama': 6,
  'Etli Nohut': 7,
  'Etli Kuru Fasulye': 7,
  'Etli Barbunya': 6,
  'Tavlu Yahni': 6,
  'Et Sote': 6,
  'Tavuk Sote': 6,
  'Fırında Tavuk': 7,
  'Fırında Köfte': 7,
  'Fırında Makarna': 7,
  'Fırında Patates': 6,
  'Fırında Sebze': 6,
  
  // 🥣 Kahvaltılık Tahıllar
  'Müsli': 6,
  'Granola': 6,
  'Yulaf Ezmesi': 6,
  'Cornflakes': 6,
  'Sütlaç': 9,
  'Puding': 6,
  'Meyveli Yoğurt': 6,
  'Chia Puding': 6,
  
  // 🌮 Wraplar
  'Tavuk Wrap': 7,
  'Et Wrap': 7,
  'Köfte Wrap': 7,
  'Falafel Wrap': 6,
  'Vegan Wrap': 6,
  'Tuna Wrap': 6,
  'Salmon Wrap': 6,
  
  // 🍳 Omlet Çeşitleri
  'Sade Omlet': 7,
  'Peynirli Omlet': 8,
  'Sebzeli Omlet': 7,
  'Mantarlı Omlet': 7,
  'Sucuklu Omlet': 8,
  'Jambonlu Omlet': 7,
  'Karışık Omlet': 7,
  
  // 🥞 Pankek & Waffle
  'Sade Pankek': 7,
  'Meyveli Pankek': 7,
  'Çikolatalı Pankek': 7,
  'Ballı Pankek': 7,
  'Sade Waffle': 7,
  'Meyveli Waffle': 7,
  'Çikolatalı Waffle': 7,
  'Dondurmalı Waffle': 7,
  
  // 🍜 Çorba Çeşitleri
  'Şehriye Çorbası': 7,
  'Arabaşı Çorbası': 6,
  'Düğün Çorbası': 6,
  'Analı Kızlı Çorba': 6,
  'Yuvalama Çorbası': 6,
  'Lebeniye Çorbası': 6,
  'Bamya Çorbası': 6,
  'Brokoli Çorbası': 6,
  'Kereviz Çorbası': 6,
  'Pırasa Çorbası': 6,
  'Lahana Çorbası': 6,
  'Sebze Çorbası': 6,
  'Tavuk Çorbası': 7,
  'Balık Çorbası': 6,
  
  // 🍢 Şişler
  'Kuzu Şiş': 7,
  'Tavuk Şiş': 8,
  'Ciğer Şiş': 6,
  'Sebzeli Şiş': 6,
  'Karides Şiş': 6,
  'Köfte Şiş': 7,
  
  // 🥘 Güveçler
  'Etli Güveç': 7,
  'Tavuklu Güveç': 7,
  'Sebzeli Güveç': 6,
  'Karides Güveç': 6,
  'Mantarlı Güveç': 6,
  
  // 🍛 Köri & Soslu Yemekler
  'Tavuk Köri': 7,
  'Köfte Köri': 6,
  'Karides Köri': 6,
  'Tavuk Fajita': 7,
  'Et Fajita': 7,
  'Tavuk Teriyaki': 6,
  'Et Teriyaki': 6,
  
  // 🥗 Diyet & Sağlıklı
  'Quinoa Salatası': 6,
  'Izgara Tavuk Salata': 7,
  'Izgara Köfte Salata': 7,
  'Ton Balıklı Salata': 7,
  'Avokadolu Salata': 6,
  'Buddha Bowl': 6,
  'Protein Bowl': 6,
  'Vegan Bowl': 6,
  'Glutensiz Pizza': 6,
  'Light Pizza': 6,
  
  // 🍕 Pizza Çeşitleri
  'Margarita': 8,
  'Sucuklu': 8,
  'Pepperoni': 7,
  'Mantarlı': 7,
  'Sebzeli': 7,
  'Ton Balıklı': 6,
  'Karidesli': 6,
  'Dört Peynirli': 7,
  'Kavurmalı': 7,
  'Pastırmalı': 7,
  'Vegan Pizza': 6,
  
  // 🍔 Burger Çeşitleri
  'Klasik Burger': 9,
  'Cheeseburger': 9,
  'Double Burger': 8,
  'Bacon Burger': 8,
  'Mushroom Burger': 7,
  'BBQ Burger': 7,
  'Jalapeno Burger': 7,
  'Fish Burger': 7,
  'Chicken Burger': 8,
  'Vegan Burger': 6,
  
  // 🌭 Dürüm & Wrap
  'Adana Dürüm': 8,
  'Urfa Dürüm': 8,
  'Tavuk Dürüm': 8,
  'Et Dürüm': 8,
  'Köfte Dürüm': 7,
  'Çiğ Köfte Dürüm': 7,
  'Tantuni Dürüm': 7,
  'Falafel Dürüm': 6,
  
  // 🥪 Sandviçler
  'Tavuklu Sandviç': 7,
  'Etli Sandviç': 7,
  'Köfteli Sandviç': 7,
  'Sucuklu Sandviç': 7,
  'Jambonlu Sandviç': 6,
  'Ton Balıklı Sandviç': 6,
  'Karidesli Sandviç': 6,
  'Vegan Sandviç': 6,
  'Club Sandviç': 7,
  'Philly Cheese Steak': 7,
  
  // 🍟 Yan Ürünler
  'Patates Kızartması': 8,
  'Elma Dilim Patates': 7,
  'Baharatlı Patates': 7,
  'Patates Tava': 6,
  'Soğan Halkası': 7,
  'Mozzarella Stick': 7,
  'Jalapeno Poppers': 6,
  'Chicken Tenders': 7,
  'Chicken Wings': 8,
  'Chicken Nuggets': 7,
  
  // 🥗 Mezeler
  'Haydari': 6,
  'Atom': 6,
  'Babagannuş': 6,
  'Muhammara': 6,
  'Şakşuka': 6,
  'Girit Ezmesi': 6,
  'Acılı Ezme': 6,
  'Patlıcan Salatası': 6,
  'Köpoğlu': 6,
  'Deniz Börülcesi': 6,
  'Piyaz': 7,
  'Humus': 7,
  'Cacık': 8,
  'Kısır': 8,
  'Çoban Salatası': 8,
  'Gavurdağı Salatası': 7,
  'Roka Salatası': 6,
  'Mevsim Salatası': 6,
  
  // 🍲 Sulu Yemekler
  'Sulu Köfte': 7,
  'Terbiyeli Köfte': 6,
  'Sulu Patates': 6,
  'Sulu Sebze': 6,
  'Zeytinyağlı Türlü': 6,
  'Zeytinyağlı Pırasa': 7,
  'Zeytinyağlı Kabak': 6,
  'Zeytinyağlı Barbunya': 7,
  'Zeytinyağlı Bakla': 6,
  
  // 🥣 Kahvaltı Çeşitleri
  'Serpme Kahvaltı': 8,
  'Kahvaltı Tabağı': 8,
  'Peynir Tabağı': 7,
  'Zeytin Tabağı': 7,
  'Reçel Tabağı': 6,
  'Bal Kaymak': 7,
  'Sahanda Yumurta': 9,
  'Omlet': 8,
  'Menemen': 10,
  'Sucuklu Yumurta': 10,
  'Pastırmalı Yumurta': 9,
  'Kaşarlı Yumurta': 8,
  'Sebzeli Yumurta': 7,
  'Haşlanmış Yumurta': 7,
  'Yumurta': 7,
  'Peynir': 8,
  'Zeytin': 8,
  'Bal': 7,
  'Kaymak': 7,
  'Tereyağı': 7,
  'Reçel': 7,
  'Tahin Pekmez': 7,
  'Simit': 10,
  'Poğaça': 9,
  'Açma': 8,
  'Börek': 8,
  'Tost': 8,
  'Pancake': 7,
  'Waffle': 7,
  'Krep': 7,
  'Müsli': 6,
  'Yulaf': 6,
  'Puding': 6,
  'Meyveli Yoğurt': 6,
  
  // 🍜 Noodle & Ramen
  'Ramen': 6,
  'Udon': 6,
  'Soba': 6,
  'Pad Thai': 6,
  'Noodle': 6,
  
  // 🍛 Etli Yemekler
  'Et Sote': 6,
  'Tavuk Sote': 6,
  'Fırında Et': 7,
  'Fırında Tavuk': 7,
  'Fırında Köfte': 7,
  'Güveç': 6,
  'Kapama': 6,
  'Yahni': 6,
  'Sulu Et': 6,
  'Haşlama': 6,
  
  // 🥟 Mantı Çeşitleri
  'Kayseri Mantısı': 9,
  'Bozkır Mantısı': 7,
  'Hingel': 6,
  'Sinop Mantısı': 6,
  'Mantı': 10,
  
  // 🍢 Köfte Çeşitleri
  'Izgara Köfte': 9,
  'Sulu Köfte': 7,
  'İzmir Köfte': 8,
  'Kadınbudu Köfte': 7,
  'İçli Köfte': 8,
  'Çiğ Köfte': 8,
  'İnegöl Köfte': 7,
  'Tekirdağ Köfte': 7,
  'Misket Köfte': 6,
  'Sultan Köfte': 6,
  
  // 🌮 Dürüm Çeşitleri
  'Adana Dürüm': 8,
  'Urfa Dürüm': 8,
  'Tavuk Dürüm': 8,
  'Et Dürüm': 8,
  'Köfte Dürüm': 7,
  'Çiğ Köfte Dürüm': 7,
  'Tantuni Dürüm': 7,
  'Falafel Dürüm': 6,
  
  // 🍲 Çorba Çeşitleri
  'Mercimek': 9,
  'Ezogelin': 9,
  'Tarhana': 8,
  'Yayla': 8,
  'Domates': 8,
  'İşkembe': 7,
  'Kelle Paça': 7,
  'Tavuk Suyu': 7,
  'Şehriye': 7,
  'Düğün': 6,
  'Yuvalama': 6,
  'Arabaşı': 6,
  
  // 🍰 Pasta & Kek
  'Pasta': 7,
  'Yaş Pasta': 7,
  'Meyveli Pasta': 7,
  'Çikolatalı Pasta': 7,
  'Kremalı Pasta': 7,
  'Köstebek Pasta': 6,
  'Muzlu Pasta': 6,
  'Çilekli Pasta': 6,
  'Kek': 7,
  'Muzlu Kek': 7,
  'Çikolatalı Kek': 7,
  'Elmalı Kek': 7,
  'Portakallı Kek': 7,
  'Havuçlu Kek': 6,
  'Kuru Üzümlü Kek': 6,
  'Cevizli Kek': 6,
  'Fındıklı Kek': 6,
  'Bademli Kek': 6,
  'Vişneli Kek': 6,
  'Kayısılı Kek': 6,
  'Şeftalili Kek': 6,
  'Kirazlı Kek': 6,
  'Frambuazlı Kek': 6,
  'Böğürtlenli Kek': 6,
  'Yaban Mersinli Kek': 6,
  'Limonlu Kek': 6,
  'Portakallı Kek': 7,
  'Mandalinalı Kek': 6,
  'Greyfurtlu Kek': 6,
  'Narlı Kek': 6,
  'İncirli Kek': 6,
  'Kayısılı Kek': 6,
  'Üzümlü Kek': 6,
  'Kuru Kayısılı Kek': 6,
  'Kuru İncirli Kek': 6,
  'Kuru Üzümlü Kek': 6,
  'Cevizli Kek': 6,
  'Fındıklı Kek': 6,
  'Bademli Kek': 6,
  'Antep Fıstıklı Kek': 7,
  'Kakuleli Kek': 5,
  'Tarçınlı Kek': 6,
  'Zencefilli Kek': 5,
  'Karanfilli Kek': 5,
  'Muskatlı Kek': 5,
  'Vanilyalı Kek': 6,
  'Bademli Kek': 6,
  'Fıstıklı Kek': 7,
  'Cevizli Kek': 6,
  'Kuru Üzümlü Kek': 6,
  'Portakallı Kek': 7,
  'Limonlu Kek': 6,
  'Muzlu Kek': 7,
  'Çikolatalı Kek': 7,
  'Havuçlu Kek': 6,
  'Elmalı Kek': 7,
  'Vişneli Kek': 6,
  'Şeftalili Kek': 6,
  'Kayısılı Kek': 6,
  'Böğürtlenli Kek': 6,
  'Yaban Mersinli Kek': 6,
  'Frambuazlı Kek': 6,
  'Kirazlı Kek': 6,
  'Narlı Kek': 6,
  'Greyfurtlu Kek': 6,
  'Mandalinalı Kek': 6,
  'Tarçınlı Kek': 6,
  'Zencefilli Kek': 5,
  'Kakuleli Kek': 5,
  'Muskatlı Kek': 5,
  'Karanfilli Kek': 5,
  'Vanilyalı Kek': 6,
  'Bademli Kek': 6,
  'Fındıklı Kek': 6,
  'Cevizli Kek': 6,
  'Antep Fıstıklı Kek': 7,
  'Fıstıklı Kek': 7,
  'Kuru Üzümlü Kek': 6,
  'Üzümlü Kek': 6,
  'Kuru Kayısılı Kek': 6,
  'Kuru İncirli Kek': 6,
  'İncirli Kek': 6,
  'Kayısılı Kek': 6,
  'Üzümlü Kek': 6,
  'Cevizli Kek': 6,
  'Fındıklı Kek': 6,
  'Bademli Kek': 6,
  'Antep Fıstıklı Kek': 7,
  'Fıstıklı Kek': 7,
  'Portakallı Kek': 7,
  'Muzlu Kek': 7,
  'Çikolatalı Kek': 7,
  'Elmalı Kek': 7,
  'Havuçlu Kek': 6,
  'Vişneli Kek': 6,
  'Şeftalili Kek': 6,
  'Kayısılı Kek': 6,
  'Böğürtlenli Kek': 6,
  'Yaban Mersinli Kek': 6,
  'Frambuazlı Kek': 6,
  'Kirazlı Kek': 6,
  'Narlı Kek': 6,
  'Greyfurtlu Kek': 6,
  'Mandalinalı Kek': 6,
  'Limonlu Kek': 6,
  'Tarçınlı Kek': 6,
  'Zencefilli Kek': 5,
  'Kakuleli Kek': 5,
  'Muskatlı Kek': 5,
  'Karanfilli Kek': 5,
  'Vanilyalı Kek': 6,
  'Bademli Kek': 6,
  'Fındıklı Kek': 6,
  'Cevizli Kek': 6,
  'Antep Fıstıklı Kek': 7,
  'Fıstıklı Kek': 7,
  'Kuru Üzümlü Kek': 6,
  'Üzümlü Kek': 6,
  'Kuru Kayısılı Kek': 6,
  'Kuru İncirli Kek': 6,
  'İncirli Kek': 6,
  'Kayısılı Kek': 6,
  'Üzümlü Kek': 6,
  'Cevizli Kek': 6,
  'Fındıklı Kek': 6,
  'Bademli Kek': 6,
  'Antep Fıstıklı Kek': 7,
  'Fıstıklı Kek': 7
};

// Mevcut foods.ts'den yemekleri çıkar
const foodsPath = path.join(__dirname, '..', 'database', 'foods.ts');
const foodsContent = fs.readFileSync(foodsPath, 'utf8');

const foodBlocks = foodsContent.match(/\{\s*"name":[^}]+\},?/g) || [];
const allFoods = foodBlocks.map(block => {
  const nameMatch = block.match(/"name":\s*"([^"]+)"/);
  const categoryMatch = block.match(/"category":\s*"([^"]+)"/);
  return {
    name: nameMatch ? nameMatch[1] : '',
    category: categoryMatch ? categoryMatch[1] : '',
    fullBlock: block,
    score: popularityScores2025[nameMatch ? nameMatch[1] : ''] || 5
  };
}).filter(f => f.name);

console.log(`Toplam yemek: ${allFoods.length}`);

// Puanlara göre sırala ve top 200'ü seç
allFoods.sort((a, b) => b.score - a.score);
const top200 = allFoods.slice(0, 200);

console.log(`\n✅ Top 200 seçildi!`);
console.log(`Ortalama popülerlik: ${(top200.reduce((sum, f) => sum + f.score, 0) / 200).toFixed(1)}/10`);

// Kategori dağılımı
const categoryDist = {};
top200.forEach(f => {
  categoryDist[f.category] = (categoryDist[f.category] || 0) + 1;
});

console.log('\n📊 Kategori Dağılımı:');
Object.entries(categoryDist)
  .sort((a, b) => b[1] - a[1])
  .forEach(([cat, count]) => {
    console.log(`  ${cat}: ${count}`);
  });

// Top 20
console.log('\n🏆 Top 20 En Popüler:');
top200.slice(0, 20).forEach((f, i) => {
  console.log(`  ${i+1}. ${f.name} (${f.score}⭐)`);
});

// Rapor kaydet
const report = {
  timestamp: new Date().toISOString(),
  source: 'Yemeksepeti 2025 + Trendyol + Yemek.com',
  summary: {
    totalOriginal: allFoods.length,
    selected: top200.length,
    removed: allFoods.length - 200,
    averageScore: (top200.reduce((sum, f) => sum + f.score, 0) / 200).toFixed(1)
  },
  categoryDistribution: categoryDist,
  top50: top200.slice(0, 50).map(f => ({ name: f.name, score: f.score, category: f.category })),
  removed: allFoods.slice(200).map(f => ({ name: f.name, score: f.score }))
};

fs.writeFileSync('top200_yemeksepeti_2025_report.json', JSON.stringify(report, null, 2));
console.log('\n📝 Rapor kaydedildi: top200_yemeksepeti_2025_report.json');
